/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as NewRouteImport } from './routes/new'
import { Route as FilesRouteImport } from './routes/files'
import { Route as ConnectRouteImport } from './routes/connect'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ChatSessionKeyRouteImport } from './routes/chat/$sessionKey'
import { Route as ApiSessionsRouteImport } from './routes/api/sessions'
import { Route as ApiSendRouteImport } from './routes/api/send'
import { Route as ApiPingRouteImport } from './routes/api/ping'
import { Route as ApiPathsRouteImport } from './routes/api/paths'
import { Route as ApiHistoryRouteImport } from './routes/api/history'
import { Route as ApiFilesListRouteImport } from './routes/api/files/list'
import { Route as ApiFilesInfoRouteImport } from './routes/api/files/info'
import { Route as ApiFilesDownloadRouteImport } from './routes/api/files/download'
import { Route as ApiFilesUploadRouteImport } from './routes/api/files/upload'
import { Route as ApiFilesDeleteRouteImport } from './routes/api/files/delete'
import { Route as ApiFilesMkdirRouteImport } from './routes/api/files/mkdir'
import { Route as ApiFilesRenameRouteImport } from './routes/api/files/rename'

const NewRoute = NewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => rootRouteImport,
} as any)
const FilesRoute = FilesRouteImport.update({
  id: '/files',
  path: '/files',
  getParentRoute: () => rootRouteImport,
} as any)
const ConnectRoute = ConnectRouteImport.update({
  id: '/connect',
  path: '/connect',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatSessionKeyRoute = ChatSessionKeyRouteImport.update({
  id: '/chat/$sessionKey',
  path: '/chat/$sessionKey',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSessionsRoute = ApiSessionsRouteImport.update({
  id: '/api/sessions',
  path: '/api/sessions',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSendRoute = ApiSendRouteImport.update({
  id: '/api/send',
  path: '/api/send',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPingRoute = ApiPingRouteImport.update({
  id: '/api/ping',
  path: '/api/ping',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPathsRoute = ApiPathsRouteImport.update({
  id: '/api/paths',
  path: '/api/paths',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHistoryRoute = ApiHistoryRouteImport.update({
  id: '/api/history',
  path: '/api/history',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiFilesListRoute = ApiFilesListRouteImport.update({
  id: '/api/files/list',
  path: '/api/files/list',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiFilesInfoRoute = ApiFilesInfoRouteImport.update({
  id: '/api/files/info',
  path: '/api/files/info',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiFilesDownloadRoute = ApiFilesDownloadRouteImport.update({
  id: '/api/files/download',
  path: '/api/files/download',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiFilesUploadRoute = ApiFilesUploadRouteImport.update({
  id: '/api/files/upload',
  path: '/api/files/upload',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiFilesDeleteRoute = ApiFilesDeleteRouteImport.update({
  id: '/api/files/delete',
  path: '/api/files/delete',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiFilesMkdirRoute = ApiFilesMkdirRouteImport.update({
  id: '/api/files/mkdir',
  path: '/api/files/mkdir',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiFilesRenameRoute = ApiFilesRenameRouteImport.update({
  id: '/api/files/rename',
  path: '/api/files/rename',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/connect': typeof ConnectRoute
  '/files': typeof FilesRoute
  '/new': typeof NewRoute
  '/api/history': typeof ApiHistoryRoute
  '/api/paths': typeof ApiPathsRoute
  '/api/ping': typeof ApiPingRoute
  '/api/send': typeof ApiSendRoute
  '/api/sessions': typeof ApiSessionsRoute
  '/chat/$sessionKey': typeof ChatSessionKeyRoute
  '/api/files/list': typeof ApiFilesListRoute
  '/api/files/info': typeof ApiFilesInfoRoute
  '/api/files/download': typeof ApiFilesDownloadRoute
  '/api/files/upload': typeof ApiFilesUploadRoute
  '/api/files/delete': typeof ApiFilesDeleteRoute
  '/api/files/mkdir': typeof ApiFilesMkdirRoute
  '/api/files/rename': typeof ApiFilesRenameRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/connect': typeof ConnectRoute
  '/files': typeof FilesRoute
  '/new': typeof NewRoute
  '/api/history': typeof ApiHistoryRoute
  '/api/paths': typeof ApiPathsRoute
  '/api/ping': typeof ApiPingRoute
  '/api/send': typeof ApiSendRoute
  '/api/sessions': typeof ApiSessionsRoute
  '/chat/$sessionKey': typeof ChatSessionKeyRoute
  '/api/files/list': typeof ApiFilesListRoute
  '/api/files/info': typeof ApiFilesInfoRoute
  '/api/files/download': typeof ApiFilesDownloadRoute
  '/api/files/upload': typeof ApiFilesUploadRoute
  '/api/files/delete': typeof ApiFilesDeleteRoute
  '/api/files/mkdir': typeof ApiFilesMkdirRoute
  '/api/files/rename': typeof ApiFilesRenameRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/connect': typeof ConnectRoute
  '/files': typeof FilesRoute
  '/new': typeof NewRoute
  '/api/history': typeof ApiHistoryRoute
  '/api/paths': typeof ApiPathsRoute
  '/api/ping': typeof ApiPingRoute
  '/api/send': typeof ApiSendRoute
  '/api/sessions': typeof ApiSessionsRoute
  '/chat/$sessionKey': typeof ChatSessionKeyRoute
  '/api/files/list': typeof ApiFilesListRoute
  '/api/files/info': typeof ApiFilesInfoRoute
  '/api/files/download': typeof ApiFilesDownloadRoute
  '/api/files/upload': typeof ApiFilesUploadRoute
  '/api/files/delete': typeof ApiFilesDeleteRoute
  '/api/files/mkdir': typeof ApiFilesMkdirRoute
  '/api/files/rename': typeof ApiFilesRenameRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/connect'
    | '/files'
    | '/new'
    | '/api/history'
    | '/api/paths'
    | '/api/ping'
    | '/api/send'
    | '/api/sessions'
    | '/chat/$sessionKey'
    | '/api/files/list'
    | '/api/files/info'
    | '/api/files/download'
    | '/api/files/upload'
    | '/api/files/delete'
    | '/api/files/mkdir'
    | '/api/files/rename'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/connect'
    | '/files'
    | '/new'
    | '/api/history'
    | '/api/paths'
    | '/api/ping'
    | '/api/send'
    | '/api/sessions'
    | '/chat/$sessionKey'
    | '/api/files/list'
    | '/api/files/info'
    | '/api/files/download'
    | '/api/files/upload'
    | '/api/files/delete'
    | '/api/files/mkdir'
    | '/api/files/rename'
  id:
    | '__root__'
    | '/'
    | '/connect'
    | '/files'
    | '/new'
    | '/api/history'
    | '/api/paths'
    | '/api/ping'
    | '/api/send'
    | '/api/sessions'
    | '/chat/$sessionKey'
    | '/api/files/list'
    | '/api/files/info'
    | '/api/files/download'
    | '/api/files/upload'
    | '/api/files/delete'
    | '/api/files/mkdir'
    | '/api/files/rename'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ConnectRoute: typeof ConnectRoute
  FilesRoute: typeof FilesRoute
  NewRoute: typeof NewRoute
  ApiHistoryRoute: typeof ApiHistoryRoute
  ApiPathsRoute: typeof ApiPathsRoute
  ApiPingRoute: typeof ApiPingRoute
  ApiSendRoute: typeof ApiSendRoute
  ApiSessionsRoute: typeof ApiSessionsRoute
  ChatSessionKeyRoute: typeof ChatSessionKeyRoute
  ApiFilesListRoute: typeof ApiFilesListRoute
  ApiFilesInfoRoute: typeof ApiFilesInfoRoute
  ApiFilesDownloadRoute: typeof ApiFilesDownloadRoute
  ApiFilesUploadRoute: typeof ApiFilesUploadRoute
  ApiFilesDeleteRoute: typeof ApiFilesDeleteRoute
  ApiFilesMkdirRoute: typeof ApiFilesMkdirRoute
  ApiFilesRenameRoute: typeof ApiFilesRenameRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/new': {
      id: '/new'
      path: '/new'
      fullPath: '/new'
      preLoaderRoute: typeof NewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/files': {
      id: '/files'
      path: '/files'
      fullPath: '/files'
      preLoaderRoute: typeof FilesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/connect': {
      id: '/connect'
      path: '/connect'
      fullPath: '/connect'
      preLoaderRoute: typeof ConnectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat/$sessionKey': {
      id: '/chat/$sessionKey'
      path: '/chat/$sessionKey'
      fullPath: '/chat/$sessionKey'
      preLoaderRoute: typeof ChatSessionKeyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/sessions': {
      id: '/api/sessions'
      path: '/api/sessions'
      fullPath: '/api/sessions'
      preLoaderRoute: typeof ApiSessionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/send': {
      id: '/api/send'
      path: '/api/send'
      fullPath: '/api/send'
      preLoaderRoute: typeof ApiSendRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ping': {
      id: '/api/ping'
      path: '/api/ping'
      fullPath: '/api/ping'
      preLoaderRoute: typeof ApiPingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/paths': {
      id: '/api/paths'
      path: '/api/paths'
      fullPath: '/api/paths'
      preLoaderRoute: typeof ApiPathsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/history': {
      id: '/api/history'
      path: '/api/history'
      fullPath: '/api/history'
      preLoaderRoute: typeof ApiHistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/files/list': {
      id: '/api/files/list'
      path: '/api/files/list'
      fullPath: '/api/files/list'
      preLoaderRoute: typeof ApiFilesListRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/files/info': {
      id: '/api/files/info'
      path: '/api/files/info'
      fullPath: '/api/files/info'
      preLoaderRoute: typeof ApiFilesInfoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/files/download': {
      id: '/api/files/download'
      path: '/api/files/download'
      fullPath: '/api/files/download'
      preLoaderRoute: typeof ApiFilesDownloadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/files/upload': {
      id: '/api/files/upload'
      path: '/api/files/upload'
      fullPath: '/api/files/upload'
      preLoaderRoute: typeof ApiFilesUploadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/files/delete': {
      id: '/api/files/delete'
      path: '/api/files/delete'
      fullPath: '/api/files/delete'
      preLoaderRoute: typeof ApiFilesDeleteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/files/mkdir': {
      id: '/api/files/mkdir'
      path: '/api/files/mkdir'
      fullPath: '/api/files/mkdir'
      preLoaderRoute: typeof ApiFilesMkdirRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/files/rename': {
      id: '/api/files/rename'
      path: '/api/files/rename'
      fullPath: '/api/files/rename'
      preLoaderRoute: typeof ApiFilesRenameRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ConnectRoute: ConnectRoute,
  FilesRoute: FilesRoute,
  NewRoute: NewRoute,
  ApiHistoryRoute: ApiHistoryRoute,
  ApiPathsRoute: ApiPathsRoute,
  ApiPingRoute: ApiPingRoute,
  ApiSendRoute: ApiSendRoute,
  ApiSessionsRoute: ApiSessionsRoute,
  ChatSessionKeyRoute: ChatSessionKeyRoute,
  ApiFilesListRoute: ApiFilesListRoute,
  ApiFilesInfoRoute: ApiFilesInfoRoute,
  ApiFilesDownloadRoute: ApiFilesDownloadRoute,
  ApiFilesUploadRoute: ApiFilesUploadRoute,
  ApiFilesDeleteRoute: ApiFilesDeleteRoute,
  ApiFilesMkdirRoute: ApiFilesMkdirRoute,
  ApiFilesRenameRoute: ApiFilesRenameRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
